import Nav from './components/Nav';
import Footer from './components/Footer';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>이문삼 - 웹 프론트엔드 개발자</title>
      </head>
      <body className="font-nexon">
        <Nav />
        <div className="max-w-5xl mx-auto mt-[120px] px-20">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
